"""Continuous Model Retraining & Concept Drift Detection Pipeline (Phase 9).

Performs:
1. Statistical concept drift analysis across all 16 extracted telemetry features.
2. Automated candidate model retraining on clean baseline telemetry and verified SOC ground-truth labels.
3. Strict promotion gates: FPR <= 2.0% and FNR <= 5.0% before canary deployment eligibility.
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any

import joblib
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

from ml.feature_engineering import FeatureExtractor, FEATURE_NAMES
from ml.train_models import ModelTrainingPipeline

logger = logging.getLogger(__name__)


@dataclass
class DriftReport:
    """Report generated by ConceptDriftDetector comparing baseline vs current telemetry."""
    is_drift_detected: bool
    overall_drift_score: float
    drifted_features: List[str]
    feature_deltas: Dict[str, float]
    sample_size_baseline: int
    sample_size_current: int
    evaluated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class ConceptDriftDetector:
    """Detects statistical shift and distribution drift across telemetry feature vectors."""

    def __init__(self, drift_threshold: float = 0.25, feature_drift_threshold: float = 0.35):
        self.drift_threshold = drift_threshold
        self.feature_drift_threshold = feature_drift_threshold

    def evaluate_drift(
        self,
        X_baseline: np.ndarray,
        X_current: np.ndarray
    ) -> DriftReport:
        """Compares feature distributions using standardized mean shift and variance comparison."""
        if len(X_baseline) == 0 or len(X_current) == 0:
            raise ValueError("Datasets cannot be empty for drift analysis")

        n_features = min(X_baseline.shape[1], X_current.shape[1])
        deltas: Dict[str, float] = {}
        drifted: List[str] = []

        eps = 1e-6
        for j in range(n_features):
            feat_name = FEATURE_NAMES[j] if j < len(FEATURE_NAMES) else f"feature_{j}"
            base_col = X_baseline[:, j]
            curr_col = X_current[:, j]

            base_mean = float(np.mean(base_col))
            base_std = float(np.std(base_col)) + eps
            curr_mean = float(np.mean(curr_col))

            # Standardized shift metric
            shift = abs(curr_mean - base_mean) / base_std
            deltas[feat_name] = round(shift, 4)

            if shift >= self.feature_drift_threshold:
                drifted.append(feat_name)

        overall_score = float(np.mean(list(deltas.values()))) if deltas else 0.0
        is_drift = (overall_score >= self.drift_threshold) or (len(drifted) >= 3)

        report = DriftReport(
            is_drift_detected=is_drift,
            overall_drift_score=round(overall_score, 4),
            drifted_features=drifted,
            feature_deltas=deltas,
            sample_size_baseline=len(X_baseline),
            sample_size_current=len(X_current)
        )

        if is_drift:
            logger.warning(
                f"CONCEPT DRIFT DETECTED! Overall score={overall_score:.3f}. Drifted features: {', '.join(drifted)}"
            )
        else:
            logger.info(f"Concept drift check clean: overall score={overall_score:.3f}")

        return report


@dataclass
class RetrainingResult:
    """Outcome of model retraining and promotion evaluation."""
    success: bool
    promotion_granted: bool
    fpr: float
    fnr: float
    message: str
    candidate_model_path: Optional[str] = None
    drift_report: Optional[Dict[str, Any]] = None
    trained_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class ModelRetrainingPipeline:
    """Automates model retraining, concept drift gating, and strict FPR/FNR promotion."""

    MAX_PERMITTED_FPR: float = 0.02  # Max 2% False Positive Rate
    MAX_PERMITTED_FNR: float = 0.05  # Max 5% False Negative Rate

    def __init__(self, model_dir: str = "ml/models"):
        self.model_dir = Path(model_dir)
        self.model_dir.mkdir(parents=True, exist_ok=True)
        self.drift_detector = ConceptDriftDetector()
        self.trainer = ModelTrainingPipeline(model_dir=str(self.model_dir))

    def run_retraining_cycle(
        self,
        X_clean_train: np.ndarray,
        X_validation_normal: np.ndarray,
        X_validation_anomalous: np.ndarray,
        X_reference_baseline: Optional[np.ndarray] = None,
        contamination: float = 0.01
    ) -> RetrainingResult:
        """Executes full retraining and promotion gating cycle."""
        # 1. Concept Drift Check (if reference data provided)
        drift_report_dict = None
        if X_reference_baseline is not None and len(X_reference_baseline) > 0:
            drift_report = self.drift_detector.evaluate_drift(
                X_baseline=X_reference_baseline,
                X_current=X_clean_train
            )
            drift_report_dict = drift_report.to_dict()

        # 2. Train candidate model on clean training data
        model, scaler = self.trainer.train_isolation_forest(
            X_train=X_clean_train,
            contamination=contamination,  # Default 1% contamination ensures FPR <= 2%
            n_estimators=50
        )

        # 3. Evaluate against holdout validation sets
        metrics = self.trainer.evaluate_model(
            X_normal=X_validation_normal,
            X_anomalous=X_validation_anomalous
        )

        fpr = metrics.get("false_positive_rate", 0.0)
        fnr = metrics.get("false_negative_rate", 0.0)

        # 4. Enforce Strict Promotion Gates
        passed_fpr = fpr <= self.MAX_PERMITTED_FPR
        passed_fnr = fnr <= self.MAX_PERMITTED_FNR
        promotion_granted = passed_fpr and passed_fnr

        if promotion_granted:
            # Atomically serialize candidate model for canary promotion
            candidate_model_path = self.model_dir / "candidate_model.pkl"
            candidate_scaler_path = self.model_dir / "candidate_scaler.pkl"
            candidate_meta_path = self.model_dir / "candidate_metadata.json"

            joblib.dump(model, candidate_model_path)
            joblib.dump(scaler, candidate_scaler_path)

            meta = {
                **self.trainer.metadata,
                "validation_fpr": fpr,
                "validation_fnr": fnr,
                "promotion_granted": True,
                "promoted_at": datetime.now(timezone.utc).isoformat()
            }
            with open(candidate_meta_path, "w", encoding="utf-8") as f:
                json.dump(meta, f, indent=2)

            message = f"Model candidate PASSED promotion gates (FPR={fpr:.1%}, FNR={fnr:.1%}). Ready for canary rollout."
            logger.info(f"RETRAINING SUCCESS: {message}")
            return RetrainingResult(
                success=True,
                promotion_granted=True,
                fpr=fpr,
                fnr=fnr,
                candidate_model_path=str(candidate_model_path),
                message=message,
                drift_report=drift_report_dict
            )
        else:
            reasons = []
            if not passed_fpr:
                reasons.append(f"FPR {fpr:.1%} exceeded threshold {self.MAX_PERMITTED_FPR:.1%}")
            if not passed_fnr:
                reasons.append(f"FNR {fnr:.1%} exceeded threshold {self.MAX_PERMITTED_FNR:.1%}")
            message = f"Model candidate REJECTED: {', '.join(reasons)}."
            logger.warning(f"RETRAINING REJECTED: {message}")
            return RetrainingResult(
                success=True,
                promotion_granted=False,
                fpr=fpr,
                fnr=fnr,
                message=message,
                drift_report=drift_report_dict
            )
