"""
Detection Agent (Phase 7)
Autonomy: Read/Score
Correlates multi-request telemetry, rule firings, and ML anomaly scores to surface high-confidence security alerts.
"""

from collections import Counter, defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
import time
from typing import Dict, List, Optional, Any
import uuid
import logging

from agents.base import AgentRole, BaseSecurityAgent, AgentAction

logger = logging.getLogger(__name__)


@dataclass
class SecurityAlert:
    """High-confidence alert generated by the Detection Agent."""
    alert_id: str
    severity: str  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    threat_category: str
    target_entity: str
    score: float  # Bounded 0.0 - 100.0
    description: str
    evidence: List[str]
    event_ids: List[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class DetectionAgent(BaseSecurityAgent):
    """
    Detection Agent specializes in finding suspicious patterns across telemetry windows.
    Operates in Read/Score mode — evaluates signals without mutating system state.
    """

    def __init__(self, name: str = "detection_agent_v1"):
        super().__init__(role=AgentRole.DETECTION, name=name)
        # Sliding buffer of recent events per entity (key: IP or user_id)
        self.entity_event_buffer: Dict[str, List[dict]] = defaultdict(list)
        self.max_buffer_per_entity = 100

    def analyze_event(
        self,
        current_event: dict,
        recent_events: Optional[List[dict]] = None
    ) -> Optional[SecurityAlert]:
        """
        Analyze current event in the context of recent entity activity.
        Surfaces SecurityAlert if compound threat conditions are detected.
        """
        t0 = time.perf_counter()
        entity_key = current_event.get("principal_ref") or current_event.get("client_ip") or "unknown"
        history = list(recent_events or self.entity_event_buffer[entity_key])

        # Add current event to history buffer
        self.entity_event_buffer[entity_key].append(current_event)
        if len(self.entity_event_buffer[entity_key]) > self.max_buffer_per_entity:
            self.entity_event_buffer[entity_key].pop(0)

        alert: Optional[SecurityAlert] = None
        evidence = []
        threat_cat = ""
        severity = "LOW"
        score = 0.0

        req_id = current_event.get("request_id", "")
        fired_rules = current_event.get("fired_rules", [])
        ml_score = float(current_event.get("ml_score", 0.0))
        risk_score = float(current_event.get("risk_score", 0.0))
        path = current_event.get("path", "")
        decision = current_event.get("decision", "ALLOW")

        # 1. Pattern: Credential Stuffing / Brute Force Spray
        if path == "/api/auth/login":
            recent_logins = [
                e for e in history[-20:]
                if e.get("path") == "/api/auth/login"
            ]
            failed_logins = [
                e for e in recent_logins
                if e.get("decision") in ("BLOCK", "LIMIT") or e.get("status_code") == 401
            ]
            if len(failed_logins) >= 4 or len(recent_logins) >= 6:
                severity = "HIGH"
                score = 85.0
                threat_cat = "CREDENTIAL_STUFFING"
                evidence.append(
                    f"Rapid login velocity detected: {len(recent_logins)} attempts ({len(failed_logins)} failures)"
                )

        # 2. Pattern: Rapid Mass Scraping of Sensitive ERP Data
        if not threat_cat:
            sensitive_endpoints = ("/api/orders", "/api/inventory", "/api/finance")
            recent_sensitive = [
                e for e in history[-25:]
                if any(e.get("path", "").startswith(p) for p in sensitive_endpoints)
            ]
            if len(recent_sensitive) >= 8:
                severity = "HIGH"
                score = 75.0
                threat_cat = "MASS_SCRAPING"
                evidence.append(
                    f"Elevated access to business records: {len(recent_sensitive)} calls in recent window"
                )

        # 3. Pattern: Privilege Escalation Reconnaissance
        if not threat_cat and (
            "R004" in fired_rules
            or ("/api/users" in path and current_event.get("method") in ("POST", "PUT", "DELETE"))
        ):
            if decision == "BLOCK" or risk_score >= 50.0:
                severity = "CRITICAL"
                score = 95.0
                threat_cat = "PRIVILEGE_ESCALATION"
                evidence.append("Unauthorized administrative privilege modification attempted")

        # 4. Pattern: Multi-Signal Compound Anomaly
        if not threat_cat and (ml_score >= 50.0 or len(fired_rules) > 0 or risk_score >= 50.0):
            compounding_factors = 0
            if ml_score >= 50.0:
                compounding_factors += 1
                evidence.append(f"ML outlier detected (score: {ml_score:.1f})")
            if len(fired_rules) > 0:
                compounding_factors += 1
                evidence.append(f"Deterministic rules triggered: {', '.join(fired_rules)}")
            if risk_score >= 50.0:
                compounding_factors += 1
                evidence.append(f"Elevated risk score: {risk_score:.1f}")

            if compounding_factors >= 2:
                severity = "HIGH" if compounding_factors == 2 else "CRITICAL"
                score = min(100.0, max(60.0, risk_score + (ml_score * 0.3)))
                threat_cat = "COMPOUND_ANOMALY"

        if evidence and score >= 50.0:
            alert = SecurityAlert(
                alert_id=f"alt-{uuid.uuid4().hex[:10]}",
                severity=severity,
                threat_category=threat_cat,
                target_entity=entity_key,
                score=round(score, 2),
                description=f"Correlated threat detected: {threat_cat} by {entity_key}",
                evidence=evidence,
                event_ids=[req_id] if req_id else []
            )

        elapsed_ms = (time.perf_counter() - t0) * 1000.0
        self._record_audit(
            target_ref=entity_key,
            input_summary={"request_id": req_id, "path": path, "history_len": len(history)},
            findings={"alert_generated": alert is not None, "severity": severity, "score": score},
            actions_proposed=[],
            execution_status="COMPLETED",
            latency_ms=elapsed_ms,
            trigger_event_id=req_id
        )

        return alert
